### ISSUE TITLE
Database connection does not work locally

### ISSUE THREAD

**Issue by AlexMcConnell** [convox-examples/rails#2]
Everything seems to work when pushed to AWS, but locally, it does not.

First, the README says that the following should exist in the docker-compose.yml, but it does not:

  volumes:
    - /var/lib/example/postgres:/var/lib/postgresql/data

Second, even if that were there, I'm guessing that's a Linux path? Because there are no such paths on a Mac.

**Comment by ianmalott** [comment]
Thanks for reporting the issue. The README was updated to use the single-path volume notation.
https://github.com/convox-examples/rails#persisting-data

```
version: '2'
services:
  database:
    image: convox/postgres
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
```

That configuration in docker-compose.yml will result in a host volume stored at `~/.convox/volumes/<app>/database/var/lib/postgresql/data/`.
